namespace igLibrary.Gfx
{
	public enum IG_GFX_PLATFORM
	{
		IG_GFX_PLATFORM_DEFAULT,
		IG_GFX_PLATFORM_DX,
		IG_GFX_PLATFORM_WII,
		IG_GFX_PLATFORM_DURANGO,
		IG_GFX_PLATFORM_ASPEN,
		IG_GFX_PLATFORM_XENON,
		IG_GFX_PLATFORM_PS3,
		IG_GFX_PLATFORM_OSX,
		IG_GFX_PLATFORM_DX11,
		IG_GFX_PLATFORM_CAFE,
		IG_GFX_PLATFORM_RASPI,
		IG_GFX_PLATFORM_NULL,
		IG_GFX_PLATFORM_ANDROID,
		IG_GFX_PLATFORM_METAL,
		IG_GFX_PLATFORM_WGL,
		IG_GFX_PLATFORM_LGTV,
		IG_GFX_PLATFORM_PS4,
		IG_GFX_PLATFORM_LINUX,
		IG_GFX_PLATFORM_MAX
	};

}