/*
	Copyright (c) 2022-2025, The igLibrary Contributors.
	igLibrary and its libraries are free software: You can redistribute it and
	its libraries under the terms of the Apache License 2.0 as published by
	The Apache Software Foundation.
	Please see the LICENSE file for more details.
*/


namespace igLibrary.Core
{
	/// <summary>
	/// The platform enum, DO NOT RELY ON THE INTEGER VALUES OF THESE, since those change between games,
	/// Rely instead on igMetaEnum
	/// </summary>
	public enum IG_CORE_PLATFORM
	{
		IG_CORE_PLATFORM_DEFAULT,
		IG_CORE_PLATFORM_DEPRECATED,
		IG_CORE_PLATFORM_DEPRECATED_2 = IG_CORE_PLATFORM_DEPRECATED,
		IG_CORE_PLATFORM_DEPRECATED_3 = IG_CORE_PLATFORM_DEPRECATED,
		IG_CORE_PLATFORM_DEPRECATED_4 = IG_CORE_PLATFORM_DEPRECATED,
		IG_CORE_PLATFORM_WIN32,
		IG_CORE_PLATFORM_WII,
		IG_CORE_PLATFORM_DURANGO,
		IG_CORE_PLATFORM_ASPEN,
		IG_CORE_PLATFORM_XENON,
		IG_CORE_PLATFORM_PS3,
		IG_CORE_PLATFORM_OSX,
		IG_CORE_PLATFORM_WIN64,
		IG_CORE_PLATFORM_CAFE,
		IG_CORE_PLATFORM_NGP,
		IG_CORE_PLATFORM_MARMALADE,
		IG_CORE_PLATFORM_RASPI,
		IG_CORE_PLATFORM_ANDROID,
		IG_CORE_PLATFORM_ASPEN64,
		IG_CORE_PLATFORM_LGTV,
		IG_CORE_PLATFORM_PS4,
		IG_CORE_PLATFORM_WP8,
		IG_CORE_PLATFORM_LINUX,
		IG_CORE_PLATFORM_MAX
	}
}