namespace igLibrary.Core
{
	//While this is really nice to have, it can't be used for reading the igz header since IG_CORE_PLATFORM changes between games, hence you see the tomfoolery happen
	public enum IG_CORE_PLATFORM
	{
		IG_CORE_PLATFORM_DEFAULT,
		IG_CORE_PLATFORM_DEPRECATED,
		IG_CORE_PLATFORM_DEPRECATED_2 = IG_CORE_PLATFORM_DEPRECATED,
		IG_CORE_PLATFORM_DEPRECATED_3 = IG_CORE_PLATFORM_DEPRECATED,
		IG_CORE_PLATFORM_DEPRECATED_4 = IG_CORE_PLATFORM_DEPRECATED,
		IG_CORE_PLATFORM_WIN32,
		IG_CORE_PLATFORM_WII,
		IG_CORE_PLATFORM_DURANGO,
		IG_CORE_PLATFORM_ASPEN,
		IG_CORE_PLATFORM_XENON,
		IG_CORE_PLATFORM_PS3,
		IG_CORE_PLATFORM_OSX,
		IG_CORE_PLATFORM_WIN64,
		IG_CORE_PLATFORM_CAFE,
		IG_CORE_PLATFORM_NGP,
		IG_CORE_PLATFORM_MARMALADE,
		IG_CORE_PLATFORM_RASPI,
		IG_CORE_PLATFORM_ANDROID,
		IG_CORE_PLATFORM_ASPEN64,
		IG_CORE_PLATFORM_LGTV,
		IG_CORE_PLATFORM_PS4,
		IG_CORE_PLATFORM_WP8,
		IG_CORE_PLATFORM_LINUX,
		IG_CORE_PLATFORM_MAX
	}
}