namespace igLibrary.Utils
{
	public enum IG_UTILS_PLAY_MODE : int
	{
		IG_UTILS_PLAY_MODE_REPEAT = 0,
		IG_UTILS_PLAY_MODE_CLAMP = 1,
		IG_UTILS_PLAY_MODE_BOUNCE = 2,
		IG_UTILS_PLAY_MODE_LOOP = 3,
		IG_UTILS_PLAY_MODE_BOUNCEONCE = 4,
		IG_UTILS_PLAY_MODE_MANUAL = 5
	}
}